### ISSUE TITLE
enable_twosided can invoke the functionality of enable_global_check by default

### ISSUE THREAD

**Issue by soumyadipghosh** [pratikvn/schwarz-lib#35]
In continuation of the issue in #27, I think it would be better if the user does not need to provide the `--enable_global_check` flag when `--enable_two_sided` is provided. I believe this flag does not need to be specified for one-sided. So it might be inconvenient to write generic scripts for submitting jobs for both one-sided and two-sided.

**Comment by pratikvn** [comment]
Doc has been fixed now.
