### ISSUE TITLE
UMFPACK installation

### ISSUE THREAD

**Issue by soumyadipghosh** [pratikvn/schwarz-lib#48]
Compiling now asks for UMFPACK directory. Is there a way to prevent that or do I have to install SuiteSparse ?

**Comment by pratikvn** [comment]
You can just [switch it off](https://github.com/pratikvn/schwarz-lib/blob/develop/CMakeLists.txt#L11) as well.

**Comment by pratikvn** [comment]
Can you go ahead and create a pull request from your branch to develop ? And we can polish it and merge it.

**Comment by soumyadipghosh** [comment]
I am actually merging the develop into event-based right now (lot of merge conflicts!) I think its better to finish this first, test if the event comm works fine and then merge that into develop. What do you say?

**Comment by pratikvn** [comment]
I can understand that there are a lot of merge conflicts and it might be more work to resolve those than to just take your code and just create brand new commits from another branch from the current develop. It will definitely be easier and much less error prone
