### ISSUE TITLE
Error with METIS linking

### ISSUE THREAD

**Issue by soumyadipghosh** [pratikvn/schwarz-lib#49]
I am getting the following error while compiling : `cannot find -lmetis`. 

I think the error is [here](https://github.com/pratikvn/schwarz-lib/blob/develop/CMakeLists.txt#L57). That condition should be opposite.

**Comment by pratikvn** [comment]
does it print out `metis inc` and `metis lib` with the paths ? Are you providing the path to metis in `METIS_DIR` ?

**Comment by soumyadipghosh** [comment]
I have METIS_DIR as an environment variable. I did not get any output for `metis inc` or `metis lib` - is this supposed to be a command?

**Comment by pratikvn** [comment]
No, I mean [this](https://github.com/pratikvn/schwarz-lib/blob/develop/CMakeLists.txt#L61) should print the values of `METIS_INCLUDE_DIR` and `METIS_LIBRARY_DIR`.

**Comment by soumyadipghosh** [comment]
No, it does not print out that
