### ISSUE TITLE
Confusion with the solution variables

### ISSUE THREAD

**Issue by soumyadipghosh** [pratikvn/schwarz-lib#50]
In the run function [here](https://github.com/pratikvn/schwarz-lib/blob/develop/source/schwarz_base.cpp#L314), there is a solution that is taken as argument. Then why is another variable `global_solution` is being created inside the function ? 

Also, the variables `local_solution` and `global_solution` are being interchanged sometimes, leading to confusion. For e.g., in exchange_boundary [here](https://github.com/pratikvn/schwarz-lib/blob/develop/source/restricted_schwarz.cpp#L798), exchange_boundary_onesided is called using `global_solution` but in the function definition [here](https://github.com/pratikvn/schwarz-lib/blob/develop/source/restricted_schwarz.cpp#L612), `local_solution` is used. There might be other places where this has occurred too.

**Comment by pratikvn** [comment]
Another variable called `global_solution` is created because in the case of GPU, I need data on the GPU. the solution variable in the run function and the `global_solution` have different executors.

**Comment by pratikvn** [comment]
Regarding the confusion on the variables in `exchange_boundary` and others, I am sorry about that. I will fix it.

**Comment by pratikvn** [comment]
The variables have been renamed now.
